name: build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  client:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: macos-latest
            generator: Xcode
            buildType: Release
            triplet: x64-osx

    env:
      BUILD_DIR: '${{ github.workspace }}/build/'

    steps:
    - uses: actions/checkout@v2

    - name: CMake
      uses: lukka/get-cmake@latest

    # Restore from cache the previously built ports. If a "cache miss" occurs, then vcpkg is bootstrapped. Since a the vcpkg.json is being used later on to install the packages when run-cmake runs, no packages are installed at this time and the input 'setupOnly:true' is mandatory.
    - name: Restore artifacts or setup vcpkg
      uses: lukka/run-vcpkg@v7
      with:
        # Location of the vcpkg submodule in the Git repository.
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        # Since the cache must be invalidated when content of the vcpkg.json file changes, let's
        # compute its hash and append this to the computed cache's key.
        appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}
        vcpkgTriplet: ${{ matrix.triplet }}
        vcpkgGitCommitId: b67fab9861239e33b722b9a44f5c96dec6ca807e
        # Ensure the vcpkg artifacts are cached, they are generated in the 'CMAKE_BINARY_DIR/vcpkg_installed' directory.
        additionalCachedPaths: ${{ env.BUILD_DIR }}/vcpkg_installed

    - name: CMake
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        buildDirectory: ${{ env.BUILD_DIR }}
        useVcpkgToolchainFile: true
        buildWithCMake: true

    - name: Test
      run: |
        cd '${{ github.workspace }}/build'
        ctest -T test
